---
- hosts: all
  become: true
  tasks:
    - name: Installing packages in ubuntu
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - apache2
      when: ansible_distribution == "Ubuntu"
    - name: Installing packages in redhat
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - httpd
      when: ansible_distribution == "Amazon"
    - name: start apache in ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    - name: start apache in redhat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Amazon"  
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/ssts-alg/static_website.git'
        dest: /var/www/html

