---
- hosts: all
  become: true
  tasks:
   - name: Installing packages
     yum:
       name: "{{ item }}"
       state: present
     with_items:
       - git
       - httpd
       - java-1.8.0-openjdk-devel

